GROUND_TRUTH_FREQUENCY_VEH1: 50
GROUND_TRUTH_FREQUENCY_VEH2: 100
DET_FREQUENCY: 10
CENTER_COR: [42.300947, -83.698649]
LATENCY_TRIAL_IDS: [1, 2]
SINGLE_VEH_TRIAL_IDS: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
TWO_VEH_TRIAL_IDS: [13, 14, 15]
PED_TRIAL_IDS: [11]
GROUND_TRUTH_FREQUENCY_PED: 10
DATE: '2023-01-05'